name: Merge All Municipalities GeoJSON

on:
  push:
    paths:
      - "geojson-israel-municipalities/**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Set up Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: '3.12'

      - name: Merge all GeoJSON files
        run: python .github/scripts/merge.py

      - name: Auto commit and push merged file if changed
        uses: stefanzweifel/git-auto-commit-action@v7.1.0
        with:
          commit_message: "chore: update merged municipalities GeoJSON [ci skip]"
          file_pattern: all_municipalities.geojson
          skip_fetch: true
          skip_dirty_check: false
